version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
    ports:
      - "5432:5432"
      
  activemq:
    image: symptoma/activemq:latest
    environment:
      ACTIVEMQ_DISALLOW_WEBCONSOLE: "true"
      ACTIVEMQ_USERNAME: "admin"
      ACTIVEMQ_PASSWORD: "admin"
      ACTIVEMQ_WEBADMIN_USERNAME: "admin"
      ACTIVEMQ_WEBADMIN_PASSWORD: "admin"
    ports:
      - "61616:61616"
      - "8161:8161"