version: "3.9"


# docker-compose  --file ./container/docker-compose.yml up -d
# docker-compose  --file ./container/docker-compose.yml up -d db_mongo
# docker-compose  --file ./container/docker-compose.yml down --remove-orphans

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
    ports:
      - "5432:5432"
      
  # activemq:
  #   image: symptoma/activemq:latest
  #   environment:
  #     ACTIVEMQ_DISALLOW_WEBCONSOLE: "true"
  #     ACTIVEMQ_USERNAME: "admin"
  #     ACTIVEMQ_PASSWORD: "admin"
  #     ACTIVEMQ_WEBADMIN_USERNAME: "admin"
  #     ACTIVEMQ_WEBADMIN_PASSWORD: "admin"
  #   ports:
  #     - "61616:61616"
  #     - "8161:8161"



  ms_company:
    container_name: ms_company_container
    image: ms_company
    links:
      - postgres:local.postgres
    # - activemq:local.activemq
    build:
      context: ../
      dockerfile: container/ms-java.Dockerfile
      args:
        PROJECT_PATH: microservices/ms-company
        PORT_APP: 8082
        JVM_ARGS: -Xmx150M -Xms60M
    environment:
      APP_SERVER_PORT: 8082
      APP_SERVER_ROOT_PATH: /company/api
      APP_SERVER_HOST: 0.0.0.0
      APP_DATASOURCE_DATABASE1_JDBC_URL: jdbc:postgresql://local.postgres:5432/postgres
      APP_DATASOURCE_DATABASE1_USERNAME: admin
      APP_DATASOURCE_DATABASE1_PASS: admin
    ports:
      - "8082:8082"
